import { Level, Semester, Options } from '../../type';

export interface CourseSeedData {
  courseCode: string;
  title: string;
  level: Level;
  semester: Semester;
  unit: string;
  option: Options;
}

export const COURSE_SEED_DATA: CourseSeedData[] = [
  // 100 Level First Semester
  {
    courseCode: 'MAT101',
    title: 'General Mathematics I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'PHY101',
    title: 'General Physics I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'PHY151',
    title: 'General Physics Lab I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '1',
    option: Options.NONE,
  },
  {
    courseCode: 'CHE101',
    title: 'General Chemistry I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'CHE141',
    title: 'General Chemistry Lab I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '1',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN101',
    title: 'Engineering Drawing I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN121',
    title: 'Workshop Practice I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST101',
    title: 'Use of English I',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST103',
    title: 'Philosophy and Logic',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST105',
    title: 'Citizenship Education',
    level: Level.FIRST,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },

  // 100 Level Second Semester
  {
    courseCode: 'MAT102',
    title: 'General Mathematics II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'PHY102',
    title: 'General Physics II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'PHY152',
    title: 'General Physics Lab II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '1',
    option: Options.NONE,
  },
  {
    courseCode: 'CHE102',
    title: 'General Chemistry II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'CHE142',
    title: 'General Chemistry Lab II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '1',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN102',
    title: 'Engineering Drawing II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN122',
    title: 'Workshop Practice II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST102',
    title: 'Use of English II',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST104',
    title: 'History & Philosophy of Science',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST106',
    title: 'Introduction to Computer',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST108',
    title: 'Entrepreneurship Development I',
    level: Level.FIRST,
    semester: Semester.SECOND,
    unit: '1',
    option: Options.NONE,
  },

  // 200 Level First Semester
  {
    courseCode: 'GEN201',
    title: 'Engineering Mathematics I',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN203',
    title: 'Engineering Drawing III',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN205',
    title: 'Workshop Practice III',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN211',
    title: 'Engineering Mechanics',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN221',
    title: 'Engineering Laboratory I',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN231',
    title: 'Basic Land Surveying',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN241',
    title: 'Materials Science I',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN251',
    title: 'Engineering Thermodynamics',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN261',
    title: 'Engineer in Society',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN293',
    title: 'Entrepreneurship Development II',
    level: Level.SECOND,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },

  // 200 Level Second Semester
  {
    courseCode: 'GEN202',
    title: 'Engineering Mathematics II',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN212',
    title: 'Strength of Materials',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN214',
    title: 'Fluid Mechanics',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN222',
    title: 'Engineering Laboratory II',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN242',
    title: 'Engineering Geology',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN252',
    title: 'Basic Engineering Material',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN272',
    title: 'Basic Electrical Engineering',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN282',
    title: 'Computer for Engineers',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN292',
    title: 'Engineering Economy',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GST222',
    title: 'Peace and Conflict Resolution',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE206',
    title: 'Introduction to Electronic Engineering',
    level: Level.SECOND,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },

  // 300 Level First Semester
  {
    courseCode: 'EEE301',
    title: 'Engineering Analysis III',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE305',
    title: 'Electromagnetic Fields and Waves',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE311',
    title: 'Network Theory I',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE321',
    title: 'Electrical/Electronic Engineering Lab I',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE331',
    title: 'Computer Organization and Architecture',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE351',
    title: 'Fundamentals of Digital Systems',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE361',
    title: 'Engineering Control Systems and Design I',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN381',
    title: 'Statistics for Engineers I',
    level: Level.THIRD,
    semester: Semester.FIRST,
    unit: '1',
    option: Options.NONE,
  },

  // 300 Level Second Semester
  {
    courseCode: 'EEE302',
    title: 'Engineering Analysis IV',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE322',
    title: 'Electrical/Electronic Engineering Lab II',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE342',
    title: 'Electrical Power and Machines',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '4',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE352',
    title: 'Electrical/Electronic Measurement and Instruments',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE354',
    title: 'Applied Electronics',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '3',
    option: Options.NONE,
  },
  {
    courseCode: 'EEE372',
    title: 'Principles of Electronic Communication',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '2',
    option: Options.NONE,
  },
  {
    courseCode: 'GEN382',
    title: 'Statistics for Engineers II',
    level: Level.THIRD,
    semester: Semester.SECOND,
    unit: '1',
    option: Options.NONE,
  },
];
