import { Level, Options, Semester } from 'src/types/course';

export const COURSES = [
  {
    courseCode: 'MAT 101',
    title: 'GENERAL MATHEMATICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 101',
    title: 'GENERAL PHYSICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 151',
    title: 'GENERAL PHYSICS LAB 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'CHE 101',
    title: 'GENERAL CHEMISTRY 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'CHE 141',
    title: 'GENERAL CHEMISTRY LAB 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'GEN 101',
    title: 'ENGINEERING DRAWING 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 121',
    title: 'WORKSHOP PRACTICE 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 101',
    title: 'USE OF ENGLISH 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 103',
    title: 'PHYLOSOPHY AND LOGIC',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 105',
    title: 'CITIZENSHIP EDUCATION',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },

  {
    courseCode: 'MAT 102',
    title: 'GENERAL MATHEMATICS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 102',
    title: 'GENERAL PHYSICS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 152',
    title: 'GENERAL PHYSICS LAB 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'CHE 102',
    title: 'GENERAL CHEMISTRY 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'CHE 142',
    title: 'GENERAL CHEMISTRY LAB 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'GEN 102',
    title: 'ENGINEERING DRAWING 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 122',
    title: 'WORKSHOP PRACTICE 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 102',
    title: 'USE OF ENGLISH 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 104',
    title: 'INTRODUCTION TO COMPUTER',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 201',
    title: 'ENTGINEERING MATHEMATICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },

  {
    courseCode: 'GEN 203',
    title: 'ENGINEERING DRAWING 3',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 205',
    title: 'WORKSHOP PRACTICE 3',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 211',
    title: 'ENGINEERING MECHANICS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 3,
  },
  {
    courseCode: 'GEN 221',
    title: 'ENGINEERING LABORATORY 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GST 108',
    title: 'ENTREPRENEURSHIP DEVELOPMENT 1',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 241',
    title: 'BASIC LAND SURVEY',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GST 251',
    title: 'MATERIAL SCIENCE 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 261',
    title: 'ENGINEERING THERMODYNAMICS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 291',
    title: 'ENGINEER IN SOCIETY',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 1,
  },
  {
    courseCode: 'GST 223',
    title: 'ENTREPRENEURSHIP DEVELOPMENT 2',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },

  {
    courseCode: 'GEN 202',
    title: 'ENGINEERING MATHEMATICS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 212',
    title: 'STRENGTH OF MATERIALS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 3,
  },
  {
    courseCode: 'GEN 214',
    title: 'FLUID MECHANICS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 222',
    title: 'ENGINEERING LABORATORY 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 242',
    title: 'ENGINEERING GEOLOGY',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 252',
    title: 'BASIC ENGINEERING MATERIAL',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 272',
    title: 'BASIC ELECTRICAL ENGINEERING',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 282',
    title: 'COMPUTER FOR ENGINEERS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 292',
    title: 'ENGINEERING ECONOMY',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GST 222',
    title: 'PEACE AND CONFLICT',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'EEE 206',
    title: 'INTRODUCTION TO ELECTRONICS ENGINEERING',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 1,
  },

  {
    courseCode: 'EEE 301',
    title: 'ENGINEERING ANALYSIS 3',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 305',
    title: 'ELECTROMAGNETIC FIELDS AND WAVES',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 311',
    title: 'NETWORK THEORY 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'EEE 321',
    title: 'ELECTRICAL/ELECTRONIC ENGINEERING LAB 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 1,
  },
  {
    courseCode: 'EEE 331',
    title: 'COMPUTER ORGANIZATION AND ARCHITECTURE',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 351',
    title: 'FUNDAMENTAL OF DIGITAL SYSTEMS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 361',
    title: 'ENGINEERING  CONTROL SYSTEMS AND DESIGN 1 ',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'GEN 381',
    title: 'STATISTICS FOR ENGINEERS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },

  {
    courseCode: 'EEE 302',
    title: 'ENGINEERING ANALYSIS 4',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 322',
    title: 'ELECTRICAL/ELECTRONIC ENGINEERING LAB 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 1,
  },
  {
    courseCode: 'EEE 342',
    title: 'ELECTRICAL POWER AND MACHINES',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 4,
  },
  {
    courseCode: 'EEE 352',
    title: 'ELECTRICAL/ELECTRONIC MEASUREMENT AND MEASURING INSTRUMENTS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'EEE 354',
    title: 'APPLIED ELECTRONICS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'EEE 372',
    title: 'PRINCIPLES OF ELECTRONIC SYSTEMS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 4,
  },
  {
    courseCode: 'GEN 382',
    title: 'STATISTICS FOR ENGINEERS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 2,
  },

  {
    courseCode: 'GEN 493',
    title: 'ENGINEERING RESEARCH METHOD',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 401',
    title: 'ELECTRICAL ENGINEERING ANALYSIS (ELECTRONICS)',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },

  {
    courseCode: 'EEE403',
    title: 'FUNDAMENTALS OF LINEAR SYSTEMS THEORY (ELECTRONICS)',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 431',
    title: 'MICROPROCESSOR SYSTEMS AND UTILIZATION',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 451',
    title: 'SEMI CONDUCTOR TECHNOLOGY',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 453',
    title: 'ADVANCED ELECTRONICS AND LAB',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 3,
  },
  {
    courseCode: 'EEE 461',
    title: 'PROCESS CONTROL',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 475',
    title: 'FIELDS AND WAVES IN COMMUNICATION',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 477',
    title: 'TELEPHONE SYSTEMS',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },

  {
    courseCode: 'EEE401',
    title: 'ELECTRICAL ENGINEERING ANALYSIS (POWER)',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 403',
    title: 'FUNDAMENTALS OF LINEAR SYSTEMS THEORY',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE431',
    title: 'MICROPROCESSOR SYSTEMS AND UTILIZATION (POWER)',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 441',
    title: 'ELECTRICAL MACHINES',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 3,
  },
  {
    courseCode: 'EEE 443',
    title: 'POWER SYSTEMS AND LAB 1',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 3,
  },
  {
    courseCode: 'EEE461',
    title: 'PROCESS CONTROL (POWER)',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE477',
    title: 'TELEPHONE SYSTEMS (POWER)',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE  401',
    title: 'ELECTRICAL ENGINEERING ANALYSIS (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE  403',
    title: 'FUNDAMENTALS OF LINEAR SYSTEMS THEORY (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE  431',
    title: 'MICROPROCESSOR SYSTEMS AND UTILIZATION (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE  461',
    title: 'PROCESS CONTROL (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'EEE  471',
    title: 'COMMUNICATIONS I (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 3,
  },
  {
    courseCode: 'EEE  473',
    title: 'COMMUNICATION ENGINEERING LAB 1 (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 1,
  },{
    courseCode: 'EEE  475',
    title: 'FIELDS AND WAVES IN COMMUNICATION (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },{
    courseCode: 'EEE  477',
    title: 'TELEPHONE SYSTEMS (Telecom)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'GEN 481',
    title: 'COMPUTER AIDED DESIGN AND MANUFACTURING',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'GEN 491',
    title: 'TECHNICAL REPORT WRITING',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 1,
  },

  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },

  {
    courseCode: 'EEE 561',
    title: 'ELECTRICAL ENGINEERING ANALYSIS AND CONTROL SYSTEM DESIGN 2',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },
  {
    courseCode: 'EEE571',
    title: 'DATA COMMUNICATION (TELECOM)',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },
  {
    courseCode: 'EEE 573',
    title: 'COMMUNICATION ENGINEERING LAB 2',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },
  {
    courseCode: 'EEE 575',
    title: 'ANTENNA AND PROPAGATION',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 577',
    title: 'WIRELESS COMMUNICATION',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 591',
    title: 'PROJECT 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 572',
    title: 'MICROWAVE COMMUNICATION ENGINEERING',
    option: Options.TELECOM,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 574',
    title: 'PRINCIPLES OF RADAR AND NAVIGATION SYSTEMS',
    option: Options.TELECOM,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 576',
    title: 'QUALITY, RELIABILITY OF COMMUNICATION SYSTEM',
    option: Options.TELECOM,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },
  {
    courseCode: 'EEE 578',
    title: 'COMMUNICATION NETWORK PLANNING AND MANAGEMENT',
    option: Options.TELECOM,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'GEN 592',
    title: 'PROFESSIONAL PRACTICE',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 531',
    title: 'INTRODUCTION TO OPERATING SYSTEMS',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 551',
    title: 'POWER ELECTRONICS',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 553',
    title: 'ELECTRONIC AND COMPUTER LAB 2',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 571',
    title: 'DATA COMMUNICATION',
    option: Options.ELECTRONICS,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 581',
    title: 'SEMINAR',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 532',
    title: 'COMPUTER APPLICATION LAB',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 552',
    title: 'ADVANCED ELECTRONICS 2',
    option: Options.ELECTRONICS,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 554',
    title: 'INTRODUCTION TO VLSI DESIGN',
    option: Options.ELECTRONICS,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 556',
    title: 'DIGITAL INSTRUMENTATION',
    option: Options.ELECTRONICS,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 558',
    title: 'QUALITY AND RELIABILITY OF ELECTRONIC AND COMPUTER SYSTEMS',
    option: Options.ELECTRONICS,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 592',
    title: 'PROJECT 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 541',
    title: 'POWER SYSTEM PLANNING, RELIABILITY AND ECONOMICS',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 543',
    title: 'POWER SYSTEM ENGINEERING LAB 2',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 545',
    title: 'HIGH VOLTAGE ENGINEERING LAB 2',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE551',
    title: 'POWER ELECTRONICS (POWER)',
    option: Options.POWER,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'GEN 591',
    title: 'ENGINEERING MANAGEMENT AND LAW',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIFTH,
    unit: 2,
  },

  {
    courseCode: 'EEE 534',
    title: 'COMPUTER NETWORKS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 542',
    title: 'ELECTRIC DRIVE SYSTEMS',
    option: Options.POWER,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 544',
    title: 'ROTATING MACHINE CONTROL',
    option: Options.POWER,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 546',
    title: 'DESIGN OF ELECTROMECHANICAL DEVICES AND MACHINES',
    option: Options.POWER,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

  {
    courseCode: 'EEE 548',
    title: 'POWER SYSTEM PROTECTION',
    option: Options.POWER,
    semester: Semester.SECOND,
    level: Level.FIFTH,
    unit: 3,
  },

];
