import { Level, Options, Semester } from 'src/types/course';

export const COURSES = [
  {
    courseCode: 'MAT 101',
    title: 'GENERAL MATHEMATICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 101',
    title: 'GENERAL PHYSICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 151',
    title: 'GENERAL PHYSICS LAB 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'CHE 101',
    title: 'GENERAL CHEMISTRY 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'CHE 141',
    title: 'GENERAL CHEMISTRY LAB 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'GEN 101',
    title: 'ENGINEERING DRAWING 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 121',
    title: 'WORKSHOP PRACTICE 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 101',
    title: 'USE OF ENGLISH 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 103',
    title: 'PHYLOSOPHY AND LOGIC',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 105',
    title: 'CITIZENSHIP EDUCATION',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 2,
  },

  {
    courseCode: 'MAT 101',
    title: 'GENERAL MATHEMATICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'MAT 102',
    title: 'GENERAL MATHEMATICS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 102',
    title: 'GENERAL PHYSICS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'PHY 152',
    title: 'GENERAL PHYSICS LAB 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'CHE 102',
    title: 'GENERAL CHEMISTRY 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 3,
  },
  {
    courseCode: 'CHE 142',
    title: 'GENERAL CHEMISTRY LAB 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 1,
  },
  {
    courseCode: 'GEN 102',
    title: 'ENGINEERING DRAWING 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 122',
    title: 'WORKSHOP PRACTICE 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 102',
    title: 'USE OF ENGLISH 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GST 104',
    title: 'INTRODUCTION TO COMPUTER',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 201',
    title: 'ENTGINEERING MATHEMATICS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },

  {
    courseCode: 'GEN 203',
    title: 'ENGINEERING DRAWING 3',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 205',
    title: 'WORKSHOP PRACTICE 3',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 211',
    title: 'ENGINEERING MECHANICS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 3,
  },
  {
    courseCode: 'GEN 221',
    title: 'ENGINEERING LABORATORY 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GST 108',
    title: 'ENTREPRENEURSHIP DEVELOPMENT 1',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FIRST,
    unit: 2,
  },
  {
    courseCode: 'GEN 241',
    title: 'BASIC LAND SURVEY',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GST 251',
    title: 'MATERIAL SCIENCE 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 261',
    title: 'ENGINEERING THERMODYNAMICS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 291',
    title: 'ENGINEER IN SOCIETY',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 1,
  },
  {
    courseCode: 'GST 223',
    title: 'ENTREPRENEURSHIP DEVELOPMENT 2',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 2,
  },

  {
    courseCode: 'GEN 202',
    title: 'ENGINEER IN SOCIETY',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 212',
    title: 'STRENGTH OF MATERIALS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.SECOND,
    unit: 3,
  },
  {
    courseCode: 'GEN 214',
    title: 'FLUID MECHANICS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 222',
    title: 'ENGINEERING LABORATORY 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 242',
    title: 'ENGINEERING GEOLOGY',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 252',
    title: 'BASIC ENGINEERING MATERIAL',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 272',
    title: 'BASIC ELECTRICAL ENGINEERING',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 282',
    title: 'COMPUTER FOR ENGINEERS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GEN 292',
    title: 'ENGINEERING ECONOMY',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'GST 222',
    title: 'PEACE AND CONFLICT',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 2,
  },
  {
    courseCode: 'EEE 206',
    title: 'INTRODUCTION TO ELECTRONICS ENGINEERING',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.SECOND,
    unit: 1,
  },

  {
    courseCode: 'EEE 301',
    title: 'ENGINEERING ANALYSIS 3',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 305',
    title: 'ELECTROMAGNETIC FIELDS AND WAVES',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 311',
    title: 'NETWORK THEORY 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'EEE 321',
    title: 'ELECTRICAL/ELECTRONIC ENGINEERING LAB 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 1,
  },
  {
    courseCode: 'EEE 331',
    title: 'COMPUTER ORGANIZATION AND ARCHITECTURE',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 351',
    title: 'FUNDAMENTAL OF DIGITAL SYSTEMS',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 361',
    title: 'ENGINEERING  CONTROL SYSTEMS AND DESIGN 1 ',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'GEN 381',
    title: 'STATISTICS FOR ENGINEERS 1',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.THIRD,
    unit: 2,
  },

  {
    courseCode: 'EEE 302',
    title: 'ENGINEERING ANALYSIS 4',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 2,
  },
  {
    courseCode: 'EEE 322',
    title: 'ELECTRICAL/ELECTRONIC ENGINEERING LAB 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 1,
  },
  {
    courseCode: 'EEE 342',
    title: 'ELECTRICAL POWER AND MACHINES',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 4,
  },
  {
    courseCode: 'EEE 352',
    title: 'ELECTRICAL/ELECTRONIC MEASUREMENT AND MEASURING INSTRUMENTS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'EEE 354',
    title: 'APPLIED ELECTRONICS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 3,
  },
  {
    courseCode: 'EEE 372',
    title: 'PRINCIPLES OF ELECTRONIC SYSTEMS',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 4,
  },
  {
    courseCode: 'GEN 382',
    title: 'STATISTICS FOR ENGINEERS 2',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.THIRD,
    unit: 2,
  },

  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
  {
    courseCode: 'GEN 481',
    title: 'COMPUTER AIDED DESINGN AND  MANUFACTURING',
    option: Options.GENERAL,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },
  {
    courseCode: 'GEN 491',
    title: 'TECHNICAL REPORT WRITING',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 1,
  },
  {
    courseCode: 'GEN 493',
    title: 'ENGINEERING RESEARCH METHOD',
    option: Options.TELECOM,
    semester: Semester.FIRST,
    level: Level.FOURTH,
    unit: 2,
  },

  {
    courseCode: 'GEN 490',
    title: 'INDUSTRIAL TRAINING (SIWES)',
    option: Options.GENERAL,
    semester: Semester.SECOND,
    level: Level.FOURTH,
    unit: 15,
  },
];
